### ISSUE TITLE
add ability to schedule announcements

### ISSUE THREAD

**Issue by andrewpbray** [qmd-lab/scheduled-docs#15]
Allow the user to add not just docs but also [announcements](https://quarto.org/docs/websites/website-tools.html#announcement-bar) to appear on the course website according to the `_schedule.yml`. It would produce a metadata file that would be merged with `_quarto.yml` to create this type of functionality:

```yml
website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Stat 20 is hiring! If you're interested in working as a tutor or reader in the spring, fill out the [New Staff Application](https://forms.gle/c5CBb1P8KTmmD5pu5). Applications received by Oct. 29th will get priority."
    type: primary
    position: below-navbar
```
